Coupon.create(coupon_code: 'ABC123', store: 'Modells')
Coupon.create(coupon_code: 'WW29nKS', store: 'Best Buy')
Coupon.create(coupon_code: 'FAST 20', store: 'Uber')
Coupon.create(coupon_code: 'FREE1', store: 'Yelp')
Coupon.create(coupon_code: 'SUMMER10', store: 'Urban Outfitter')
